services:
  app:
    image: todo-front-dev
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:3000"
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-front-dev
