version: "3.8"
services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
  app:
    image: todo-front-dev
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:3000"
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - todo_front_dev_data:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-front-dev
volumes:
  todo_front_dev_data:
