version: "3.8"
services:
  frontend:
    image: patientor-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    container_name: patientor-front-dev
    depends_on:
      - backend
  backend:
    image: patientor-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    container_name: patientor-backend-dev
